//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choreographies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Choreographies()
        {
            this.ChoreographyMembers = new HashSet<ChoreographyMembers>();
            this.DanceGroupChoreographies = new HashSet<DanceGroupChoreographies>();
            this.DanceSelectionChoreographies = new HashSet<DanceSelectionChoreographies>();
            this.EventChoreographies = new HashSet<EventChoreographies>();
            this.Performances = new HashSet<Performances>();
        }
    
        public int ChoreographyID { get; set; }
        public string ChoreographyName { get; set; }
        public string ChoreographyDesc { get; set; }
        public Nullable<int> Lookup_DisciplineID { get; set; }
        public Nullable<int> Lookup_DanceStyleID { get; set; }
        public Nullable<int> Lookup_AgeCategoryID { get; set; }
    
        public virtual Lookup_AgeCategories Lookup_AgeCategories { get; set; }
        public virtual Lookup_DanceStyles Lookup_DanceStyles { get; set; }
        public virtual Lookup_Disciplines Lookup_Disciplines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoreographyMembers> ChoreographyMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceGroupChoreographies> DanceGroupChoreographies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceSelectionChoreographies> DanceSelectionChoreographies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventChoreographies> EventChoreographies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performances> Performances { get; set; }
    }
}
