//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanceGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanceGroups()
        {
            this.DanceGroupChoreographies = new HashSet<DanceGroupChoreographies>();
            this.DanceGroupLocations = new HashSet<DanceGroupLocations>();
            this.DanceGroupMembers = new HashSet<DanceGroupMembers>();
            this.DanceGroupPeriods = new HashSet<DanceGroupPeriods>();
            this.DanceGroupStaff = new HashSet<DanceGroupStaff>();
            this.DanceSelectionDanceGroups = new HashSet<DanceSelectionDanceGroups>();
        }
    
        public int DanceGroupID { get; set; }
        public string DanceGroupName { get; set; }
        public string DanceGroupDesc { get; set; }
        public Nullable<int> AgeCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceGroupChoreographies> DanceGroupChoreographies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceGroupLocations> DanceGroupLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceGroupMembers> DanceGroupMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceGroupPeriods> DanceGroupPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceGroupStaff> DanceGroupStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceSelectionDanceGroups> DanceSelectionDanceGroups { get; set; }
        public virtual Lookup_AgeCategories Lookup_AgeCategories { get; set; }
    }
}
