//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanceSelections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanceSelections()
        {
            this.DanceSelectionChoreographies = new HashSet<DanceSelectionChoreographies>();
            this.DanceSelectionDanceGroups = new HashSet<DanceSelectionDanceGroups>();
            this.DanceSelectionLocations = new HashSet<DanceSelectionLocations>();
            this.DanceSelectionMembers = new HashSet<DanceSelectionMembers>();
            this.DanceSelectionStaff = new HashSet<DanceSelectionStaff>();
            this.Trainings = new HashSet<Trainings>();
        }
    
        public int DanceSelectionID { get; set; }
        public string DanceSelectionName { get; set; }
        public string DanceSelectionDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceSelectionChoreographies> DanceSelectionChoreographies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceSelectionDanceGroups> DanceSelectionDanceGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceSelectionLocations> DanceSelectionLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceSelectionMembers> DanceSelectionMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanceSelectionStaff> DanceSelectionStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainings> Trainings { get; set; }
    }
}
