//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DFAppEntities : DbContext
    {
        public DFAppEntities()
            : base("name=DFAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choreographies> Choreographies { get; set; }
        public virtual DbSet<ChoreographyChoreographers> ChoreographyChoreographers { get; set; }
        public virtual DbSet<ChoreographyMembers> ChoreographyMembers { get; set; }
        public virtual DbSet<ContactData> ContactData { get; set; }
        public virtual DbSet<Costumes> Costumes { get; set; }
        public virtual DbSet<DanceGroupChoreographies> DanceGroupChoreographies { get; set; }
        public virtual DbSet<DanceGroupLocations> DanceGroupLocations { get; set; }
        public virtual DbSet<DanceGroupMembers> DanceGroupMembers { get; set; }
        public virtual DbSet<DanceGroupPeriods> DanceGroupPeriods { get; set; }
        public virtual DbSet<DanceGroups> DanceGroups { get; set; }
        public virtual DbSet<DanceGroupStaff> DanceGroupStaff { get; set; }
        public virtual DbSet<DanceSelectionChoreographies> DanceSelectionChoreographies { get; set; }
        public virtual DbSet<DanceSelectionDanceGroups> DanceSelectionDanceGroups { get; set; }
        public virtual DbSet<DanceSelectionLocations> DanceSelectionLocations { get; set; }
        public virtual DbSet<DanceSelectionMembers> DanceSelectionMembers { get; set; }
        public virtual DbSet<DanceSelectionPeriods> DanceSelectionPeriods { get; set; }
        public virtual DbSet<DanceSelections> DanceSelections { get; set; }
        public virtual DbSet<DanceSelectionStaff> DanceSelectionStaff { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<DocumentTags> DocumentTags { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<EventChoreographies> EventChoreographies { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Lookup_AgeCategories> Lookup_AgeCategories { get; set; }
        public virtual DbSet<Lookup_DanceStyles> Lookup_DanceStyles { get; set; }
        public virtual DbSet<Lookup_Disciplines> Lookup_Disciplines { get; set; }
        public virtual DbSet<Lookup_DocumentTags> Lookup_DocumentTags { get; set; }
        public virtual DbSet<Lookup_EventTypes> Lookup_EventTypes { get; set; }
        public virtual DbSet<MemberDocuments> MemberDocuments { get; set; }
        public virtual DbSet<MemberImages> MemberImages { get; set; }
        public virtual DbSet<MemberPaymentItems> MemberPaymentItems { get; set; }
        public virtual DbSet<MemberPayments> MemberPayments { get; set; }
        public virtual DbSet<MemberPaymentsForCompanions> MemberPaymentsForCompanions { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Outfits> Outfits { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Performances> Performances { get; set; }
        public virtual DbSet<Periods> Periods { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<TrainingMemberPresenceRegistrations> TrainingMemberPresenceRegistrations { get; set; }
        public virtual DbSet<Trainings> Trainings { get; set; }
        public virtual DbSet<TrainingStaff> TrainingStaff { get; set; }
        public virtual DbSet<UserDocuments> UserDocuments { get; set; }
        public virtual DbSet<UserGroupMembers> UserGroupMembers { get; set; }
        public virtual DbSet<UserGroupPermissions> UserGroupPermissions { get; set; }
        public virtual DbSet<UserGroups> UserGroups { get; set; }
        public virtual DbSet<UserImages> UserImages { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<DocumentMetadata> DocumentMetadata { get; set; }
    }
}
