//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTags
    {
        public int DocumentID { get; set; }
        public int Lookup_TagID { get; set; }
        public string Note { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Lookup_DocumentTags Lookup_DocumentTags { get; set; }
    }
}
