//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documents()
        {
            this.DocumentTags = new HashSet<DocumentTags>();
            this.MemberDocuments = new HashSet<MemberDocuments>();
            this.UserDocuments = new HashSet<UserDocuments>();
        }
    
        public int DocumentID { get; set; }
        public string DocumentName { get; set; }
        public string DocumentDesc { get; set; }
        public string DocumentCodedName { get; set; }
        public string DocumentFileName { get; set; }
        public string DocumentFileExtension { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public string DocumentPath { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentTags> DocumentTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberDocuments> MemberDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDocuments> UserDocuments { get; set; }
        public virtual DocumentMetadata DocumentMetadata { get; set; }
    }
}
