//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainings()
        {
            this.TrainingMemberPresenceRegistrations = new HashSet<TrainingMemberPresenceRegistrations>();
        }
    
        public int TrainingID { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public int TrainingLocationID { get; set; }
        public Nullable<int> TrainingDanceGroupID { get; set; }
        public Nullable<int> TrainingDanceSelectionID { get; set; }
        public string WeekDay { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> TrainerUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingMemberPresenceRegistrations> TrainingMemberPresenceRegistrations { get; set; }
        public virtual DanceGroups DanceGroups { get; set; }
        public virtual DanceSelections DanceSelections { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Users Users { get; set; }
    }
}
