//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF.DB.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingMemberPresenceRegistrations
    {
        public int TrainingID { get; set; }
        public int MemberID { get; set; }
        public bool IsPresent { get; set; }
        public Nullable<bool> AbsenceJustified { get; set; }
        public string AbsenceNote { get; set; }
        public bool IsOnline { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Trainings Trainings { get; set; }
    }
}
